In [2]:
import h3 
import xarray as xr
import rasterio
from shapely.geometry import Polygon
import geopandas as gpd
import numpy as np
import os
import pandas as pd
import data_prep as dp

In [3]:
%load_ext autoreload
%autoreload 2

Se leen los datos de velocidad del viento que contienen toda la extension del proyecto. Se busca utilizar la extensión del mismo para definir la región a llenar con hexágonos.

In [2]:
# wind_speed
path = '/home/jta/Documentos/raster_variables/ahpAmbiental/COL_wind-speed_10m.tif'
ds_wind = rasterio.open(path)

Para generar una malla de hexagonos se genera un poligono que contiene los limites del raster.

In [3]:
ext = ds_wind.bounds
up_l_corner = (ext[-1],ext[0])
up_r_corner = (ext[-1],ext[2])
down_l_corner = (ext[1],ext[0])
down_r_cornor = (ext[1],ext[2])
# Creacion poligono
polygon = Polygon(
    (
        down_l_corner,down_r_cornor,
        up_r_corner,up_l_corner
    )
)

la funcion `geo_to_cells` genera la malla de hexagonos, a esta se le debe suministrar la resolucion con el tamano de los hexagonos. Esta regresa una lista de `str` que contienen el codigo de cada hexagonos

In [4]:
# Creacion de una malla de hexagonos
resolution = 8
hexagons = h3.geo_to_cells(polygon, resolution)

De cada hexagono se pueden extraer los vertices de cada hexagono, esto se puede convertir en un geodataframe para almacenar la informacion asociada a cada variable. Donde cada columna del geodataframe corresponde a un atributo especifico

In [5]:
# Genera lista con la extension de 
geometry = [Polygon(h3.cell_to_boundary(h)) for h in hexagons]

gdf_hex = gpd.GeoDataFrame(
    {'h3': hexagons},
    geometry=geometry,
    crs="EPSG:4326"
)
# cambio de epsg
epsg_on = '9377'
gdf_hex = gdf_hex.to_crs(epsg_on)

In [51]:
# Lectura de datos
path = '/home/jta/Documentos/raster_variables/datos_cris/especies_densidades/especies_migratorias_final'
gdf_migratorias = gpd.read_file(path)
# convertir 
gdf_migratorias = gdf_migratorias.to_crs(epsg_on)

In [52]:
if gdf_hex.crs != gdf_migratorias.crs:
   gdf_migratorias =gdf_migratorias.to_crs(gdf_hex.crs)

# 2. Realizar el Spatial Join
# Esto asigna a cada punto el ID del hexágono donde se encuentra
# 'predicate="within"' es lo inverso a contains, ideal para puntos dentro de polis
puntos_con_hex = gpd.sjoin(gdf_migratorias, gdf_hex, how="inner", predicate="within")

In [53]:
df_unicas = puntos_con_hex.groupby('h3').nunique()

In [54]:
df_unicas

,phylum,class,order,family,species,decimalLat,decimalLon,geometry,index_right,varaible
h3,,,,,,,,,,
88e660025bfffff,1,1,3,4,4,1,1,1,1,1
88e660029bfffff,1,1,3,4,5,1,1,1,1,1
88e66002c9fffff,1,1,2,2,2,1,1,1,1,1
88e6600513fffff,1,2,2,2,4,8,8,8,1,1
88e66005a3fffff,1,1,2,2,2,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...
88f16bb835fffff,1,1,1,1,2,1,1,1,1,1
88f16bb883fffff,1,1,3,3,4,1,1,1,1,1
88f16bb8e5fffff,1,1,1,1,1,1,1,1,1,1
88f16bb941fffff,1,1,2,2,3,1,1,1,1,1
88f16bbb4dfffff,1,1,1,1,1,1,1,1,1,1

In [ ]:
def relacion_especie(h3_code):

    # busca el número de especies
    mask = df_unicas.index == h3_code
    df_slice = df_unicas[mask]

    if df_slice.empty:
        especies = 0
    else:
        especies = df_unicas.at[h3_code,'species']
    
    return especies

In [55]:
# Extraccion numero de especies
gdf_hex['species_unicas'] = gdf_hex['h3'].map(df_unicas['species']).fillna(0).astype(int)

In [56]:
gdf_hex

,h3,geometry,varaible,species_unicas
0,88e74ab153fffff,"POLYGON ((5325672.764 2270751.835, 5326192.707...",0,0
1,88e74e391bfffff,"POLYGON ((5277632.122 2453118.543, 5278155.352...",0,0
2,88ef9e3307fffff,"POLYGON ((4714660.425 1703928.869, 4715184.234...",0,0
3,88e75c583bfffff,"POLYGON ((5400394.434 3191045.991, 5400910.973...",0,0
4,88f1693865fffff,"POLYGON ((3845240.623 1229251.959, 3845730.612...",0,0
...,...,...,...,...
1305221,88e758b033fffff,"POLYGON ((5428545.561 2785409.567, 5429063.776...",0,0
1305222,88eeb31139fffff,"POLYGON ((5181829.665 1182933.908, 5182326.141...",0,0
1305223,88ef9e12c7fffff,"POLYGON ((4690862.544 1837828.981, 4691391.747...",0,0
1305224,88f1691825fffff,"POLYGON ((3797756.295 1251269.183, 3798246.824...",0,0
1305225,88e76a571bfffff,"POLYGON ((5052953.546 2647235.922, 5053486.109...",0,0

In [ ]:
gdf_hex.to_file('especies_unicas')

/tmp/ipykernel_9817/758144650.py:1: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  gdf_hex.to_file('especies_unicas')
/home/jta/miniconda3/envs/cds/lib/python3.14/site-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'species_unicas' to 'species_un'
  ogr_write(

In [ ]:

# 3. Contar cuántos puntos hay por cada índice de hexágono
# Asumimos que el índice de h3_hex es único (ej. el h3 address)
conteo_puntos = puntos_con_hex.groupby("index_right").size()

# 4. Asignar el conteo al geodataframe original de hexágonos
h3_hex.loc[:,"num_avistamientos"] = conteo_puntos
h3_hex.loc[:,"num_avistamientos"] = h3_hex["num_avistamientos"].fillna(0) # Los que no tuvieron puntos son 0

# 5. Calcular densidad (Vectorizado - sin bucles)
#Area en km2 (asumiendo que el CRS proyectado está en metros, si es geográfico lat/lon es diferente)
factor = 1e6
h3_hex.loc[:,"area_km2"] = h3_hex.geometry.area / factor
h3_hex.loc[:,"densidad"] = h3_hex["num_avistamientos"] / h3_hex["area_km2"]

In [ ]:
def densidad_especies(
        h3_hex:gpd.GeoDataFrame,
        gdf_especies:gpd.GeoDataFrame
    ) -> gpd.GeoDataFrame:

    if h3_hex.crs != gdf_migratorias.crs:
        gdf_especies = gdf_especies.to_crs(h3_hex.crs)

    # 2. Realizar el Spatial Join
    # Esto asigna a cada punto el ID del hexágono donde se encuentra
    # 'predicate="within"' es lo inverso a contains, ideal para puntos dentro de polis
    puntos_con_hex = gpd.sjoin(gdf_especies, h3_hex, how="inner", predicate="within")

    # 3. Contar cuántos puntos hay por cada índice de hexágono
    # Asumimos que el índice de h3_hex es único (ej. el h3 address)
    conteo_puntos = puntos_con_hex.groupby("index_right").size()

    # 4. Asignar el conteo al geodataframe original de hexágonos
    h3_hex.loc[:,"num_avistamientos"] = conteo_puntos
    h3_hex.loc[:,"num_avistamientos"] = h3_hex["num_avistamientos"].fillna(0) # Los que no tuvieron puntos son 0

    # 5. Calcular densidad (Vectorizado - sin bucles)
    #Area en km2 (asumiendo que el CRS proyectado está en metros, si es geográfico lat/lon es diferente)
    factor = 1e6
    h3_hex.loc[:,"area_km2"] = h3_hex.geometry.area / factor
    h3_hex.loc[:,"densidad"] = h3_hex["num_avistamientos"] / h3_hex["area_km2"]
    
    return h3_hex

In [ ]:
h3_especies = densidad_especies(gdf_hex,gdf_migratorias)

## Media de cada variable

Manejo de ráster con H3. Las variables binarias se deben llevar a H3, para hacer multplicaciones. Respecto a las variables continuas se debe aplicar la media contenida dentro de cada hexágono.

In [ ]:
path_pendientes = '/home/jta/Documentos/raster_variables/raster_data/Pendientes.tif'
ds = xr.open_dataarray(path_pendientes)

In [ ]:
def raster_2_h3(
        geometry:gpd.GeoDataFrame,
        raster:xr.DataArray,
    ) -> gpd.GeoDataFrame:
    # Intenta recortar el raster con la geometría
    clip_values = raster.rio.clip([geometry])
        
    # Calcula el promedio
    mean_val = clip_values.values.mean()

    return mean_val

In [ ]:
# Implementacion zonal_stats
from rasterstats import zonal_stats

# Convierte el raster a formato compatible (necesita ruta o array + transform)
stats = zonal_stats(
    gdf_hex,
    ds.values[0],                    # array 2D
    affine=ds.rio.transform(),       # transformación geoespacial
    stats=['mean'],
    nodata=ds.rio.nodata
)
da = ds['band_data']
gdf_hex['pendiente'] = gdf_hex['geometry'].apply(raster_2_h3,raster=da)

/home/jta/miniconda3/envs/cds/lib/python3.14/site-packages/rasterstats/io.py:335: NodataWarning: Setting nodata to -999; specify nodata explicitly
  warnings.warn(

KeyboardInterrupt:

## Extraer variables binarias

In [6]:
path_files = r'/home/jta/Documentos/raster_variables/SIG'
files = os.listdir(path_files)

In [7]:
path = r'/home/jta/Documentos/raster_variables/Vento-Tabla General de Variables Multidimensionales.xlsx'
df_vars = pd.read_excel(path,)

In [8]:
def name_var(
        cod:str,
        df=df_vars
    ):
    mask = df['Código'] == cod
    var = df[mask].iloc[0,-1]
    return var

In [9]:
# Creacion diccionario info
dict_vars = dict()
# Creacion de geodataframes
for file in files:
    # Extraccion variable
    var = name_var(file)
    # Creacion de geodaframe
    full_path = os.path.join(
        path_files,
        file
    )
    gdf = gpd.read_file(full_path)
    # Almacenamiento
    dict_vars[var] = gdf

/home/jta/miniconda3/envs/cds/lib/python3.14/site-packages/pyogrio/raw.py:200: RuntimeWarning: organizePolygons() received an unexpected geometry.  Either a polygon with interior rings, or a polygon with less than 4 points, or a non-Polygon geometry.  Return arguments as a collection.
  return ogr_read(
/home/jta/miniconda3/envs/cds/lib/python3.14/site-packages/pyogrio/raw.py:200: RuntimeWarning: Geometry of polygon of fid 1655 cannot be translated to Simple Geometry. All polygons will be contained in a multipolygon.
  return ogr_read(

In [20]:
gdf = dict_vars['Fallas activas y zonas de fractura']

In [21]:
if gdf_hex.crs != gdf.crs:
   gdf = gdf.to_crs(gdf_hex.crs)
    
# 2. Realizar el Spatial Join
# Esto asigna a cada punto el ID del hexágono donde se encuentra
# 'predicate="within"' es lo inverso a contains, ideal para puntos dentro de polis
puntos_con_hex = gpd.sjoin(gdf, gdf_hex, how="inner", predicate="within")

In [43]:
x = ~gdf_hex['h3'].map(puntos_con_hex['h3']).isna()
x.sum()

np.int64(0)

In [49]:
mask = gdf_hex['h3'].isin(puntos_con_hex['h3']).astype(int)
gdf_hex['varaible'] = mask

In [50]:
gdf_hex

,h3,geometry,varaible
0,88e74ab153fffff,"POLYGON ((5325672.764 2270751.835, 5326192.707...",0
1,88e74e391bfffff,"POLYGON ((5277632.122 2453118.543, 5278155.352...",0
2,88ef9e3307fffff,"POLYGON ((4714660.425 1703928.869, 4715184.234...",0
3,88e75c583bfffff,"POLYGON ((5400394.434 3191045.991, 5400910.973...",0
4,88f1693865fffff,"POLYGON ((3845240.623 1229251.959, 3845730.612...",0
...,...,...,...
1305221,88e758b033fffff,"POLYGON ((5428545.561 2785409.567, 5429063.776...",0
1305222,88eeb31139fffff,"POLYGON ((5181829.665 1182933.908, 5182326.141...",0
1305223,88ef9e12c7fffff,"POLYGON ((4690862.544 1837828.981, 4691391.747...",0
1305224,88f1691825fffff,"POLYGON ((3797756.295 1251269.183, 3798246.824...",0
1305225,88e76a571bfffff,"POLYGON ((5052953.546 2647235.922, 5053486.109...",0

In [ ]:
# 3. Contar cuántos puntos hay por cada índice de hexágono
# Asumimos que el índice de gdf_hex es único (ej. el h3 address)
conteo_puntos = puntos_con_hex.groupby("index_right").size()

# 4. Asignar el conteo al geodataframe original de hexágonos
gdf_hex.loc[:,"num_avistamientos"] = conteo_puntos
gdf_hex.loc[:,"num_avistamientos"] = gdf_hex["num_avistamientos"].fillna(0) # Los que no tuvieron puntos son 0

# 5. Calcular densidad (Vectorizado - sin bucles)
#Area en km2 (asumiendo que el CRS proyectado está en metros, si es geográfico lat/lon es diferente)
factor = 1e6
gdf_hex.loc[:,"area_km2"] = gdf_hex.geometry.area / factor
gdf_hex.loc[:,"densidad"] = gdf_hex["num_avistamientos"] / gdf_hex["area_km2"]

return gdf_hex

# Revision objeto que prepara los datos

In [1]:
# wind_speed
path = 'COL_wind-speed_10m.tif'
ds_wind = rasterio.open(path)
crs = 'EPSG:9377'
resolution = 8

NameError: name 'rasterio' is not defined

In [58]:
h3_module = dp.h3_grid(
    raster=ds_wind,
    resolution=8,
    crs=crs
)

In [61]:
h3_grid = h3_module.create_grid()

In [41]:
# Prueba variables binarias
path = '/home/jta/Documentos/raster_variables/SIG/AMB-001-AR'
gdf_runap = gpd.read_file(path)

In [63]:
binaria = h3_module.var_binarias(gdf_runap)

In [52]:
h3_module._grid_cache

AttributeError: 'h3_grid' object has no attribute '_grid_cache'

In [25]:
h3_grid['runap'] = binaria

In [26]:
h3_grid.to_file('runap_binaria')

## Primera prueba herramienta

In [7]:
import h3 
import xarray as xr
import rasterio
from shapely.geometry import Polygon
import geopandas as gpd
import numpy as np
import os
import pandas as pd
import data_prep as dp

In [8]:
# wind_speed
path = 'COL_wind-speed_10m.tif'
ds_wind = rasterio.open(path)
crs = 'EPSG:9377'
resolution = 8

In [9]:
h3_module = dp.h3_grid(
    raster=ds_wind,
    resolution=8,
    crs=crs
)

In [10]:
path = 'codigo_tipos(in).csv'
df_data = pd.read_csv(path,sep=';',encoding='latin-1')
df_data = df_data.drop(['Criterio'], axis = 1)
df_data = df_data[~df_data['Subcriterio'].isna()]

In [11]:
list(df_data['Subcriterio'].unique())

['Areas', 'Especies', 'Condiciones', 'Amenazas']

In [ ]:
from ahp import Transformer
ahp = Transformer()
distinct_criterios = list(df_data['Subcriterio'].unique()) 



archivos_prueba =[
    # "AMB-001-AR",
    #  "AMB-003-A",
    # "AMB-004-A", 
    # "AMB-005-A", 
    "AMB-007-AT", "AMB-010-A", 
    "AMB-011-A", "AMB-012-A", "AMB-013-A", "AMB-014-A", "AMB-015-A", "AMB-016-A", 
    # "AMB-019-A", "AMB-020-A", "AMB-021-A", "AMB-029-AT", "AMB-032-A", "AMB-033-A", 
    # "AMB-034-A", "AMB-035-A", "AMB-036-A", "AMB-037-A", "AMB-038-A", "AMB-039-A"
]
total = pd.DataFrame()
#Creacion de la geometria
geometry = h3_module.create_grid()
for criterio in distinct_criterios:
    mask1 = (df_data['Subcriterio'] == criterio)
    mask2 = (df_data['Codigo'].isin(archivos_prueba))
    df_data_slice = df_data[mask1 & mask2].reset_index(drop=True)
    if(len(df_data_slice) == 0):
        continue

    path = 'vars_ambiental_ahp/'
    gdf_h3 = h3_module.vars_ahp(path,df_data_slice)
    calc_cols = gdf_h3.iloc[:,2:]
    gdf_h3 = gdf_h3.iloc[:,:2]


    num_var = len(calc_cols.columns)
    matrix = ahp.simulate_matrices(1, num_var)
    pesos = ahp.calculate_weights(matrix)
    total[criterio] = (calc_cols*pesos).sum(axis = 1)

df_final = pd.concat(
    [geometry,total],
    axis=1,
)

Empezando variable AMB-010-A...
Empezando variable AMB-011-A...

/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: organizePolygons() received an unexpected geometry.  Either a polygon with interior rings, or a polygon with less than 4 points, or a non-Polygon geometry.  Return arguments as a collection.
  return ogr_read(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: Geometry of polygon of fid 1655 cannot be translated to Simple Geometry. All polygons will be contained in a multipolygon.
  return ogr_read(

Empezando variable AMB-012-A...
Empezando variable AMB-013-A...
Empezando variable AMB-014-A...
Empezando variable AMB-015-A...
Empezando variable AMB-016-A...
Empezando variable AMB-007-AT...